import React, { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useScan } from '../lib/ScanContext'

export default function Download() {
  const { id } = useParams()
  const { currentScan } = useScan()
  const isLive = id === 'current' && currentScan?.docxUrl
  const [versionName, setVersionName] = useState(currentScan?.jobTitle || 'Senior Data Analyst — Knova One')
  const [saved, setSaved] = useState(false)

  return (
    <div className="max-w-xl mx-auto px-6 py-20 text-center">
      <p className="eyebrow mb-2">Done</p>
      <h1 className="font-display text-3xl font-semibold mb-6">Your resume is ready</h1>

      <div className="bg-white border border-ink/15 rounded-sm p-8 mb-8 -rotate-1">
        <div className="w-16 h-16 mx-auto mb-4 border-2 border-mint rounded-sm flex items-center justify-center font-mono text-mint-dim text-xs">
          DOCX
        </div>
        <p className="font-mono text-sm text-ink/60">resume_final.docx</p>
      </div>

      {isLive ? (
        <a href={currentScan.docxUrl} download="resume_final.docx" className="btn-primary w-full mb-6 block">
          Download DOCX
        </a>
      ) : (
        <button
          className="btn-primary w-full mb-6"
          onClick={() => alert('This will download the DOCX generated by POST /scans/export once connected to the backend.')}
        >
          Download DOCX
        </button>
      )}

      <div className="text-left">
        <label className="block font-sans text-sm font-semibold mb-2">Save this version as</label>
        <div className="flex gap-3">
          <input className="paper-input" value={versionName} onChange={(e) => setVersionName(e.target.value)} />
          <button onClick={() => setSaved(true)} className="btn-ghost whitespace-nowrap">Save</button>
        </div>
        {saved && <p className="font-mono text-xs text-mint-dim mt-2">Saved to your dashboard.</p>}
      </div>

      <Link to="/dashboard" className="inline-block mt-10 text-sm text-ink/60 hover:text-ink">
        ← Back to dashboard
      </Link>
    </div>
  )
}
